name: flutter_heiyanquan
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # 状态管理
  get: ^4.7.2

  # 获取包信息
  package_info_plus: 8.3.1

  # 本地存储
  shared_preferences: ^2.5.3

  # 网络请求
  dio: ^5.9.0

  # 组件库
  ducafe_ui_core: ^1.0.6

  # icon
  flutter_svg: ^2.2.2
  badges: 3.1.2
  extended_image: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
