name: flutter_heiyanquan
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # 状态管理
  get: ^4.7.2

  # 获取包信息
  package_info_plus: 8.3.1

  # 本地存储
  shared_preferences: ^2.5.3

  # 网络请求
  dio: ^5.9.0

  # 组件库
  ducafe_ui_core: ^1.0.6

  # 主题
  adaptive_theme: ^3.7.2

  # svg
  flutter_svg: ^2.2.2

  # 图片缓存
  cached_network_image: ^3.4.1

  badges: 3.1.2
  extended_image: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 图标
  # 使用命令: dart run icons_launcher:create
  icons_launcher: ^3.0.3

# app 图标
icons_launcher:
  image_path: "assets/icons/ic_logo.png"
  platforms:
    android:
      enable: true
      notification_image: "assets/icons/ic_foreground.png"
      # adaptive_background_color: '#ffffff'
      adaptive_background_image: "assets/icons/ic_background.png"
      adaptive_foreground_image: "assets/icons/ic_foreground.png"
    ios:
      enable: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  # 字体下载：https://fonts.google.com/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
